version: '3.1'

services: 
  build: 
    context: .
    dockerfile: Dockerfile
  generator: 
    image: aspnetcore/generator:latest
    ports:
      - "8080:80"
      
# TO RUN THIS: docker-compose up